### ISSUE TITLE
Crash if a Windows 1.2.16 client connects

### ISSUE THREAD

**Issue by viric** [umurmur/umurmur#95]
There is a crash in strncpy in a build with shm (--enable-shmapi), when a Windows 1.2.16 client connects. I guess it has something to do with the client certificate there created.

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6df194f in __strncpy_sse2_unaligned () from /nix/store/gwl3ppqj4i730nhd4f50ncl5jc4n97ks-glibc-2.23/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6df194f in __strncpy_sse2_unaligned () from /nix/store/gwl3ppqj4i730nhd4f50ncl5jc4n97ks-glibc-2.23/lib/libc.so.6
#1  0x0000000000416e81 in Sharedmemory_update () at sharedmemory.c:72
#2  0x000000000040ad8d in Server_runLoop (pollfds=0x64ad50) at server.c:205
#3  0x000000000040b596 in Server_run () at server.c:336
#4  0x0000000000407958 in main (argc=4, argv=0x7fffffffc478) at main.c:368
(gdb) up
#1  0x0000000000416e81 in Sharedmemory_update () at sharedmemory.c:72
72                                      strncpy( shmptr->client[cc].username, client_itr->username, 120 );
(gdb) print shmptr->client[cc].username
$3 = '\000' <repeats 120 times>
(gdb) print client_itr->username
$4 = 0x0
```

**Comment by snowblind** [comment]
I ran Windows 1.2.16 client on my RPI server here and it does not crash here..

Did it work with versions before that client version.

What OS and machine type are you running umurmurd on? I think some kind of x86 since sse2 in function name.

**Comment by troxor** [comment]
Given the age of this issue and lack of activity, marking as closed for now. 0.3.0 is available, so if the issue recurs there, please report back with reproduction steps!
